## YAML Template.
---
server:
  port: 8080
  servlet:
    contextPath: /

spring:

  profiles:
    active: remote

  datasource:
    url: jdbc:mysql://localhost:3306/atmone?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: ENC(ljTzugwusT5J2d5P2k2rMA==)
    password: ENC(QxFS4mHsY24mG1jAFXqzNriynopOaafM)
    hikari:
      maximum-pool-size: 20
    driverClassName: com.mysql.jdbc.Driver

  jpa:
    generate-ddl: false
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate:
        ddl-auto: none
        proc:
          param_null_passing: true

application:
  encrypted: ENC(uTSqb9grs1+vUv3iN8lItC0kl65lMG+8)

jasypt:
  encryptor:
    bean: encryptorBean